# ===============================
# Server
# ===============================
server.port=9090
spring.application.name=api-gateway

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Gateway Routes
# ===============================

# -------- AUTH SERVICE --------
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# -------- HOSPITAL SERVICE --------
spring.cloud.gateway.routes[1].id=hospital-service
spring.cloud.gateway.routes[1].uri=lb://hospital-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/hospital/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# -------- PATIENT SERVICE --------
spring.cloud.gateway.routes[2].id=patient-service
spring.cloud.gateway.routes[2].uri=lb://patient-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/patient/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# -------- ADMIN SERVICE --------
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://admin-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# ===============================
# Logging (for debugging)
# ===============================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO
